import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// components (zakładam, że wszystkie mają `export default`)
import Header from "./components/Header";
import Hero from "./components/Hero";
import Logo from "./components/Logo";
import AboutSection from "./components/AboutSection";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}